### ISSUE TITLE
Show character professions

### ISSUE THREAD

**Issue by Kaeseknacker** [derwhite/whitez_mplus#14]
Blizzard API let us show professions:
` /profile/wow/character/{realmSlug}/{characterName}/professions`

Currently we can't show the profession talent tree, but we can show how much skillpoints every charakter has per profession.

**Comment by derwhite** [comment]
Yeah... I saw this, too. But i don't know where to show this infomation... 

I think all this leads more Up to a new Tab on the Side, where we can put more advanced charakter information Like, Tier Sets, professions and so on.

**Comment by Kaeseknacker** [comment]
Yes, I would also suggest a new table to solve the "space" problem.
In total 4 tables:

1. General overview (iLvl, T-Set, Professions, Achievments, talents?, ...)
2. M+ Overview (Total Score, highest key-lvls per Dungeon)
3. runs current week
4. runs previos week

**Comment by derwhite** [comment]
I would like to see the General overview more to the right ^^ because, its more player detailed stuff and i want M+ Overview still on Focus to the page. We also need to mention that, i want to make sure this page runs without a given battle.net Dev API key, so that just this General overview didn't shows up.
