### ISSUE TITLE
wowhead tooltips are broken after the sticky table header updates

### ISSUE THREAD

**Issue by Kaeseknacker** [derwhite/whitez_mplus#19]
@derwhite your changes for #16 messed up the wowhead tooltips.

compare commit
1a9c918 (working)
with
0a4daab (messed up)

**Comment by derwhite** [comment]
thank you for reporting...
i looked into it and i think i found a solution and made it more clear to css that i only want my table ^^ 6787c3bc6f26e0512acc0c03e30c9858ebf0d372

**Comment by Kaeseknacker** [comment]
Almost fixed. The right edge of the tooltip is still slightly off.
It has something to do with the line `top: 0;` in:
```
table th {
    position: sticky;
    top: 0;
    padding: 5px;
    margin: 20px;
    font-size: 18px;
}
```
If you remove this row, the tooltip is fixed but the sticky table header doesn't work anymore.
I think the correct solution is to define an own css table class instead of reconfigure the general `table` class/tag.
But therefore I have to take a closer look at the CSS basics.

Currently the .css file looks more like "copy& paste - I don't know what I'm doing here" ^^

**Comment by derwhite** [comment]
> Currently the .css file looks more like "copy& paste - I don't know what I'm doing here" ^^

That's exactly what i'm doing ! Like my Readme says, i'm far away from be a professional and i have fun to build some small scripts that can do things 4 me. I don't want to study things for hours to exacly know every detail. So i got an example of it, what i want to do, so i pick it up and use it. if it works, great... so next ;<

So problem is, why the hell is that stupid tooltip changes to <th>... i think thats table head... so now i changes it, that only in 'mytabs' th is affected....

For me this Project works really well and it just runs... I know that the Code isn't optimized, beautyful or something. I'm fine if it works and i dont want to spend to much time into it.

I hope that 

> Currently the .css file looks more like "copy& paste - I don't know what I'm doing here" ^^

is just a bad joke, but its bothers me a lot right now. I personally didn't know any experiecend programmer at all. I have at work nothing to do with writing programs... and i searched google for hours, to do the html tables, styles, tabs, font sizes, column sizes.... and so on.
If u can to something like this from 0, okay all right... if u don't like my code, i'm fine... You don't need to do anything here. I did it because you asked me, so i put another good amout of hours in rewriting it. I looked up a few hours how git works... 

I like if u have fun, to rewrite some functions, make better lists, use a Class 4 players.... and so on. For me, i don't need that kind of fancy staff, but if u have fun with it, do it.... You made so much changes that i complete lost track, what was changed and its no problem for me, but pls don't make of my code, so i don't make fun of your code.
